{% set name = "smqtk-image-io" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_image_io-{{ version }}.tar.gz
  sha256: 7c8a17e6c7a3fd4ccf1c29f15f42d8b05262857bc614e6b4266e89881e093b0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - pillow >=8.2.0
    - numpy >=1.21
    - smqtk-core >=0.19
    - smqtk-dataprovider >=0.16.0

test:
  imports:
    - smqtk_image_io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/smqtk-image-io/
  summary: SMQTK Image IO
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
